FROM apache/superset:latest

USER root

RUN apt-get update && apt-get install -y \
    gcc g++ libsasl2-dev libsasl2-modules \
    python3-dev libssl-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip install pyhive[hive] thrift thrift-sasl sasl

USER superset
